# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
import numpy as np

In [8]:
a = np.random.random((2,3))
print(a)

[[0.86192359 0.97434355 0.92435716]
 [0.76582008 0.85125831 0.64514695]]


In [6]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [9]:
a.shape

(2, 3)

In [10]:
a

array([[0.86192359, 0.97434355, 0.92435716],
       [0.76582008, 0.85125831, 0.64514695]])

In [11]:
a.size

6

In [12]:
# to access elemnts of "a" ""
a[1,0]

0.7658200751718622

In [15]:
#to access the whole first raw:
a[0]

array([0.86192359, 0.97434355, 0.92435716])

In [16]:
# to access the entire first coloumn
a[:,0]

array([0.86192359, 0.76582008])

In [17]:
# to access the entire first raw

a[0,:]

array([0.86192359, 0.97434355, 0.92435716])

In [19]:
b = np.random.random((2,3,5))

In [22]:
b

array([[[0.42060204, 0.56970584, 0.10806005, 0.65497008, 0.01223958],
        [0.60977759, 0.15467531, 0.0747262 , 0.46330143, 0.27021488],
        [0.0368339 , 0.35209482, 0.65116355, 0.86467884, 0.53664305]],

       [[0.92624183, 0.37157248, 0.23581512, 0.45396882, 0.75231566],
        [0.45478451, 0.09969037, 0.16607647, 0.47333084, 0.21099855],
        [0.40870962, 0.08853592, 0.95282105, 0.77453338, 0.59137708]]])

In [23]:
b[0,2,:] # 3rd raw of first matrix

array([0.0368339 , 0.35209482, 0.65116355, 0.86467884, 0.53664305])

In [21]:
b[0,:,2]# the third column of first matrix

array([0.10806005, 0.0747262 , 0.65116355])

In [24]:
b[1,2,:] # second marrix, 3rd raw

array([0.40870962, 0.08853592, 0.95282105, 0.77453338, 0.59137708])

In [25]:
b[1,:,4]# 2nd matrix, 5th column

array([0.75231566, 0.21099855, 0.59137708])

In [26]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))
print (first)
print(second)

[[0.93304747 0.81305581 0.56883489 0.89283833]
 [0.92021087 0.43240147 0.12285728 0.85662928]
 [0.9125593  0.48169961 0.21677791 0.30770703]]
[[0.13001513 0.50330419 0.35039848 0.91486103]
 [0.53087813 0.45461316 0.67506746 0.89679227]
 [0.63318957 0.10261772 0.506902   0.83770713]]


In [27]:
# to sum values: it only adds the same size matrixes
sum1 = np.add(first, second)
print(sum1)

[[1.06306261 1.31636    0.91923337 1.80769936]
 [1.451089   0.88701464 0.79792474 1.75342155]
 [1.54574887 0.58431733 0.72367991 1.14541416]]


In [29]:
multiply1 = np.multiply(first, second)
print(multiply1)

[[0.12131029 0.4092144  0.19931888 0.81682299]
 [0.48851983 0.1965754  0.08293695 0.76821851]
 [0.57782303 0.04943092 0.10988516 0.25776838]]


In [30]:
test = np.random.random((3, 4))*10 #(it multiplies each outcome of the matrix by 10)
test

array([[3.13847184, 4.45666717, 4.66331821, 8.63226342],
       [0.29331487, 9.35928211, 4.81427287, 3.27081912],
       [2.58840098, 8.54578769, 3.69244784, 9.00566939]])

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [31]:
# your code here
a = np.ones([2, 3])
b = np.ones([2, 3])
a + b

array([[2., 2., 2.],
       [2., 2., 2.]])

Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [34]:
# your code here

c= np.ones([3, 2])

# we cannot add 2 matrix with different size

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [37]:
# your code here
d = np.transpose(c)
print (d)
e=a+d
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


Which combination of arrays are you able to multiply with each other? Why?

In [39]:
# your code here
a*b
a*d

array([[1., 1., 1.],
       [1., 1., 1.]])

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [40]:
# your code here
lst = list(range(11))
e = np.square (lst)
print(e)


[  0   1   4   9  16  25  36  49  64  81 100]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [41]:
# your code here
import numpy as np
f = np.zeros((10, 10), int)

diagonal_entries = np.random.randint(low = 0, high = 100, size = 10)

np.fill_diagonal(f, diagonal_entries)

print(f)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0 65  0  0  0  0  0  0  0  0]
 [ 0  0 61  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0]
 [ 0  0  0  0  0 75  0  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0]
 [ 0  0  0  0  0  0  0 59  0  0]
 [ 0  0  0  0  0  0  0  0 45  0]
 [ 0  0  0  0  0  0  0  0  0 69]]


In [42]:
# this is from teacher, but why it is like this, with commas? 
np.eye(10)*np.random.randint(100, size=10)

array([[13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 93.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 51.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 21.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 52.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 79.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 37.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 61.]])