# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [5]:
import numpy

In [6]:
import numpy as np

In [4]:
a = np.random.random((2,3))

In [5]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [6]:
a.shape

(2, 3)

In [7]:
a

array([[0.0098168 , 0.42429746, 0.20364204],
       [0.64746523, 0.50448007, 0.73197769]])

In [8]:
a.size

6

In [9]:
# to access elemnts of a
a[1,0]

0.6474652271541338

In [10]:
#to access the whole first rwa
a[0]

array([0.0098168 , 0.42429746, 0.20364204])

In [11]:
# to access the entire first coloumn
a[:,0]

array([0.0098168 , 0.64746523])

In [12]:
# to access the entire first raw

a[0,:]

array([0.0098168 , 0.42429746, 0.20364204])

In [13]:
b = np.random.random((2,3, 5))

In [14]:
b

array([[[0.4651991 , 0.00732707, 0.91851408, 0.97432991, 0.12523771],
        [0.77239414, 0.40108134, 0.42733518, 0.18379675, 0.00656287],
        [0.3325594 , 0.29343531, 0.72780907, 0.41633669, 0.70881967]],

       [[0.45006203, 0.54662887, 0.39800787, 0.63203104, 0.22248475],
        [0.49938462, 0.04427604, 0.07619448, 0.7872718 , 0.12333168],
        [0.15678856, 0.94600203, 0.75110934, 0.60193699, 0.18783738]]])

In [15]:
b[0,2,:] # 3rd raw of first matrix

array([0.3325594 , 0.29343531, 0.72780907, 0.41633669, 0.70881967])

In [16]:
b[0,:,2]# the third column of first matrix

array([0.91851408, 0.42733518, 0.72780907])

In [24]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))
print (first)
print(second)

[[0.31448692 0.53830833 0.67176334 0.06951106]
 [0.871173   0.76733354 0.85089922 0.01135776]
 [0.57041817 0.29744204 0.4729963  0.42571086]]
[[0.75164473 0.02963557 0.84057472 0.03295919]
 [0.4892179  0.50068081 0.83460754 0.73458675]
 [0.89430834 0.48959593 0.17247899 0.72688564]]


In [25]:
# to sum values: it only adds the same size matrixes
sum1 = np.add(first, second)
print(sum1)

[[1.06613165 0.5679439  1.51233806 0.10247025]
 [1.36039089 1.26801434 1.68550676 0.74594451]
 [1.46472651 0.78703797 0.6454753  1.1525965 ]]


In [31]:
multi1 = np.multiply(first, second)
print(multi1)

[[0.23638244 0.01595307 0.56466728 0.00229103]
 [0.42619342 0.38418918 0.7101669  0.00834326]
 [0.51012973 0.14562641 0.08158193 0.30944311]]


In [22]:
test = np.random.random((3, 4)) * 10 #(it multiplies each outcome of the matrix by 10)
test

array([[6.73083001, 8.82238024, 3.32164366, 9.65676234],
       [8.31440671, 2.5950162 , 2.39983959, 4.10877749],
       [4.08840658, 9.4361885 , 4.83437289, 0.95752049]])

In [2]:
# your code here


In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [9]:
# your code here
a = [[1, 1, 1],[1, 1, 1] ]
a = np.array(a)
print (a)

b = [[1, 1, 1],[1, 1, 1] ]
b = np.array(b)
print (b)

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [10]:
# your code here
c = [[1, 1], [1, 1], [1, 1]]
c = np.array(c)
print(c)

[[1 1]
 [1 1]
 [1 1]]


Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [14]:
# your code here
d = np.transpose(c)
print (d)

[[1 1 1]
 [1 1 1]]


Which combination of arrays are you able to multiply with each other? Why?

In [5]:
# your code here


Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [16]:
# your code here
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
e = np.square (lst)
print(e)


[  0   1   4   9  16  25  36  49  64  81 100]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [22]:
# your code here
f = np.zeros((10, 10), int)

diagonal_entries = np.random.randint(low = 0, high = 100, size = 10)

np.fill_diagonal(f, diagonal_entries)

print(f)

[[48  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 0  0 79  0  0  0  0  0  0  0]
 [ 0  0  0 48  0  0  0  0  0  0]
 [ 0  0  0  0 93  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0]
 [ 0  0  0  0  0  0  0 28  0  0]
 [ 0  0  0  0  0  0  0  0 62  0]
 [ 0  0  0  0  0  0  0  0  0 32]]
