# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
import numpy

In [2]:
import numpy as np

In [25]:
a = np.random.random((2,3))

In [5]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [20]:
a.shape

(2, 3, 5)

In [26]:
a

array([[0.07674126, 0.94893493, 0.84285824],
       [0.99768272, 0.09913538, 0.57007298]])

In [21]:
a.size

30

In [23]:
# to access elemnts of a
a[1,0]

array([0.28995706, 0.66985724, 0.45039197, 0.23316075, 0.59516153])

In [16]:
#to access the whole first rwa
a[0]

array([0.08837812, 0.40067094, 0.30183705])

In [17]:
# to access the entire first coloumn
a[:,0]

array([0.08837812, 0.57747406])

In [18]:
# to access the entire first raw

a[0,:]

array([0.08837812, 0.40067094, 0.30183705])

In [27]:
b = np.random.random((2,3, 5))

In [28]:
b

array([[[0.42782652, 0.36969084, 0.82609071, 0.83166043, 0.58649267],
        [0.78779245, 0.00964452, 0.75493864, 0.09897077, 0.77062703],
        [0.54413459, 0.04937721, 0.22112484, 0.6999044 , 0.79031502]],

       [[0.48311553, 0.58959667, 0.33747918, 0.3797165 , 0.90860036],
        [0.04403119, 0.43207914, 0.14251407, 0.16290487, 0.17444684],
        [0.65402379, 0.03251416, 0.19163598, 0.09508389, 0.06829827]]])

In [29]:
b[0,2,:] # 3rd raw of first matrix

array([0.54413459, 0.04937721, 0.22112484, 0.6999044 , 0.79031502])

In [30]:
b[0,:,2]# the third column of first matrix

array([0.82609071, 0.75493864, 0.22112484])

In [ ]:
# the array is mutable 

In [2]:
# your code here


In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [1]:
# your code here


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [3]:
# your code here


Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [4]:
# your code here


Which combination of arrays are you able to multiply with each other? Why?

In [5]:
# your code here


Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [6]:
# your code here


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [7]:
# your code here
